apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-app
      tier: frontend
  template:
    metadata:
      labels:
        app: netflix-app
        tier: frontend
    spec:
      containers:
        - name: netflix-app
          image: nagasatishdocker/netflix-app:latest
          ports:
            - containerPort: 3000
            
  -----------------
  
apiVersion: v1
kind: Service
metadata:
  name: astro
spec:
  selector:
    app: astro
    tier: frontend

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: Nodeport
  
  
